package com.example.ui

enum class AppLanguage(val code: String, val displayName: String, val englishName: String) {
    ENGLISH("en", "English", "English"),
    SPANISH("es", "Español", "Spanish"),
    FRENCH("fr", "Français", "French"),
    GERMAN("de", "Deutsch", "German"),
    ARMENIAN("hy", "Հայերեն", "Armenian"),
    RUSSIAN("ru", "Русский", "Russian"),
    JAPANESE("ja", "日本語", "Japanese")
}

enum class AppCurrency(val code: String, val symbol: String, val usdExchangeRate: Double) {
    USD("USD", "$", 1.0),
    EUR("EUR", "€", 0.92),
    GBP("GBP", "£", 0.79),
    AMD("AMD", "֏", 388.0),
    RUB("RUB", "₽", 91.5),
    JPY("JPY", "¥", 156.4)
}

object Localization {
    private val translations = mapOf(
        AppLanguage.ENGLISH to mapOf(
            "app_title" to "Wallet Expense Analytics",
            "nav_dashboard" to "Dashboard",
            "nav_wallet" to "Google Wallet",
            "nav_insights" to "AI Insights",
            "nav_settings" to "Settings",
            "total_expenses" to "Monthly Expenses",
            "currency_distribution" to "Spending Categories",
            "wallet_status_active" to "Sync Hook: Connected to Google Wallet & GPay Notifications",
            "sync_now" to "Sync Wallet Cards",
            "sync_desc" to "Import transactions from simulated Google Wallet NFC passes and loyalty cards.",
            "add_manual" to "New Expense",
            "merchant" to "Merchant",
            "amount" to "Amount",
            "category" to "Category",
            "currency" to "Currency",
            "source" to "Card / Source",
            "notes" to "Notes (Optional)",
            "save" to "Save Transaction",
            "cancel" to "Cancel",
            "delete" to "Delete",
            "language" to "Interface Language",
            "pref_currency" to "Preferred Currency",
            "ai_insights_title" to "Gemini Spending Advisor",
            "ai_btn_generate" to "Analyze Spending Habits",
            "ai_generating" to "Asking Gemini to review files & notifications...",
            "ai_last_analyzed" to "Last updated:",
            "data_retrieved" to "Found %d transactions.",
            "empty_state_text" to "No wallet transactions recorded. Tap 'Sync Wallet Cards' to simulate Google Wallet imports or add one manually!",
            "card_visa" to "Google Wallet (Visa **** 7741)",
            "card_master" to "Google Wallet (Mastercard **** 3329)",
            "card_amex" to "Google Wallet (Amex **** 9951)",
            "card_loyalty" to "Google Wallet (Simulated Pass Receipt)",
            "manual" to "Manual Entry",
            "cat_food" to "Food & Dining",
            "cat_transport" to "Transport & Fuel",
            "cat_shopping" to "Shopping & Retail",
            "cat_entertainment" to "Entertainment",
            "cat_utilities" to "Bills & Utilities",
            "cat_other" to "Other Expenses",
            "wallet_pass_simulator" to "Simulate Google Wallet Pass Generation",
            "pass_title" to "Push Digital Pass / Ticket Receipt",
            "pass_btn" to "Add to Google Wallet",
            "pass_sent_title" to "NFC Pass Generated!",
            "pass_sent_desc" to "The custom recipe/payment card was successfully linked with Google Wallet. It simulated an immediate NFC payment receipt of",
            "clear_all_data" to "Clear All Data",
            "about_app" to "About Wallet Expense Analytics",
            "about_desc" to "An offline-first personal ledger simulating smart direct synchronizations with Google Wallet NFC events. Automatically aggregates, translates, and filters spending layouts with built-in Gemini Generative AI advice.",
            "feedback_synced" to "Wallet synchronization completed! Found %d transactions.",
            "field_required" to "Please enter a valid merchant and positive amount."
        ),
        AppLanguage.SPANISH to mapOf(
            "app_title" to "Análisis de Gastos de Cartera",
            "nav_dashboard" to "Panel",
            "nav_wallet" to "Google Wallet",
            "nav_insights" to "Análisis IA",
            "nav_settings" to "Ajustes",
            "total_expenses" to "Gastos Mensuales",
            "currency_distribution" to "Categorías de Gasto",
            "wallet_status_active" to "Sincronización: Conectado a notificaciones de Google Wallet y GPay",
            "sync_now" to "Sincronizar Tarjetas",
            "sync_desc" to "Importar transacciones desde pases NFC simulados de Google Wallet y tarjetas de fidelidad.",
            "add_manual" to "Nuevo Gasto",
            "merchant" to "Comercio",
            "amount" to "Monto",
            "category" to "Categoría",
            "currency" to "Moneda",
            "source" to "Tarjeta / Origen",
            "notes" to "Notas (Opcional)",
            "save" to "Guardar Transacción",
            "cancel" to "Cancelar",
            "delete" to "Eliminar",
            "language" to "Idioma de la Interfaz",
            "pref_currency" to "Moneda Preferida",
            "ai_insights_title" to "Asesor de Gastos Gemini",
            "ai_btn_generate" to "Analizar Hábitos de Gasto",
            "ai_generating" to "Consultando a Gemini sobre archivos y transacciones...",
            "ai_last_analyzed" to "Última actualización:",
            "data_retrieved" to "Se encontraron %d transacciones.",
            "empty_state_text" to "No hay transacciones registradas. ¡Toca 'Sincronizar Tarjetas' para simular Google Wallet o añade una manualmente!",
            "card_visa" to "Google Wallet (Visa **** 7741)",
            "card_master" to "Google Wallet (Mastercard **** 3329)",
            "card_amex" to "Google Wallet (Amex **** 9951)",
            "card_loyalty" to "Google Wallet (Recibo de pase simulado)",
            "manual" to "Entrada Manual",
            "cat_food" to "Comida y Restaurantes",
            "cat_transport" to "Transporte y Gasolina",
            "cat_shopping" to "Compras y Tiendas",
            "cat_entertainment" to "Entretenimiento",
            "cat_utilities" to "Servicios y Facturas",
            "cat_other" to "Otros Gastos",
            "wallet_pass_simulator" to "Simular Pase de Google Wallet",
            "pass_title" to "Generar Recibo Digital de Pase",
            "pass_btn" to "Añadir a Google Wallet",
            "pass_sent_title" to "¡Pase NFC Generado!",
            "pass_sent_desc" to "El pase/tarjeta se sincronizó correctamente con Google Wallet. Se simuló un recibo de pago instantáneo de",
            "clear_all_data" to "Borrar Todos los Datos",
            "about_app" to "Acerca de la Aplicación",
            "about_desc" to "Un libro contable sin conexión que simula sincronización directa con eventos de Google Wallet NFC. Agrupa, traduce y analiza los gastos en tiempo real con recomendaciones de IA.",
            "feedback_synced" to "¡Sincronización completada! %d transacciones cargadas.",
            "field_required" to "Ingrese un comercio válido y un monto mayor a cero."
        ),
        AppLanguage.FRENCH to mapOf(
            "app_title" to "Analyse des Dépenses Portefeuille",
            "nav_dashboard" to "Tableau de Bord",
            "nav_wallet" to "Google Wallet",
            "nav_insights" to "Analyses IA",
            "nav_settings" to "Paramètres",
            "total_expenses" to "Dépenses Mensuelles",
            "currency_distribution" to "Catégories de Dépenses",
            "wallet_status_active" to "Statut : Synchronisé aux notifications Google Wallet & GPay",
            "sync_now" to "Synchroniser les Cartes",
            "sync_desc" to "Importer des transactions à partir de cartes NFC Google Wallet et de cartes de fidélité simulées.",
            "add_manual" to "Nouvelle Dépense",
            "merchant" to "Commerce",
            "amount" to "Montant",
            "category" to "Catégorie",
            "currency" to "Devise",
            "source" to "Carte / Source",
            "notes" to "Notes (Optionnel)",
            "save" to "Enregistrer",
            "cancel" to "Annuler",
            "delete" to "Supprimer",
            "language" to "Langue de l'Interface",
            "pref_currency" to "Devise Préférée",
            "ai_insights_title" to "Conseiller Budget Gemini",
            "ai_btn_generate" to "Analyser les Dépenses",
            "ai_generating" to "Analyse de Gemini en cours...",
            "ai_last_analyzed" to "Dernière mise à jour :",
            "data_retrieved" to "%d transactions récupérées.",
            "empty_state_text" to "Aucune transaction enregistrée. Appuyez sur 'Synchroniser les Cartes' pour simuler des transactions Google Wallet !",
            "card_visa" to "Google Wallet (Visa **** 7741)",
            "card_master" to "Google Wallet (Mastercard **** 3329)",
            "card_amex" to "Google Wallet (Amex **** 9951)",
            "card_loyalty" to "Google Wallet (Reçu de carte simulé)",
            "manual" to "Saisie Manuelle",
            "cat_food" to "Alimentation & Repas",
            "cat_transport" to "Transports & Carburant",
            "cat_shopping" to "Achats & Boutiques",
            "cat_entertainment" to "Divertissement",
            "cat_utilities" to "Factures & Services",
            "cat_other" to "Autres Dépenses",
            "wallet_pass_simulator" to "Simuler un Ticket Google Wallet",
            "pass_title" to "Envoyer un Ticket Numérique",
            "pass_btn" to "Ajouter à Google Wallet",
            "pass_sent_title" to "Ticket NFC Généré !",
            "pass_sent_desc" to "La carte de fidélité a été ajoutée à Google Wallet. Reçu instantané simulé :",
            "clear_all_data" to "Effacer Toutes les Données",
            "about_app" to "À Propos",
            "about_desc" to "Un grand livre financier hors ligne simulant des synchronisations intelligentes avec des paiements NFC Google Wallet.",
            "feedback_synced" to "Synchronisation réussie ! %d transactions chargées.",
            "field_required" to "Veuillez entrer un commerce valide et un montant positif."
        ),
        AppLanguage.GERMAN to mapOf(
            "app_title" to "Wallet Ausgaben-Analyse",
            "nav_dashboard" to "Dashboard",
            "nav_wallet" to "Google Wallet",
            "nav_insights" to "KI-Analysen",
            "nav_settings" to "Einstellungen",
            "total_expenses" to "Monatliche Ausgaben",
            "currency_distribution" to "Ausgabenkategorien",
            "wallet_status_active" to "Sync: Verbunden mit Google Wallet & GPay Benachrichtigungen",
            "sync_now" to "Wallet synchronisieren",
            "sync_desc" to "Transaktionen aus simulierten NFC-Karten und Wallet-Pässen importieren.",
            "add_manual" to "Neue Ausgabe",
            "merchant" to "Händler",
            "amount" to "Betrag",
            "category" to "Kategorie",
            "currency" to "Währung",
            "source" to "Karte / Quelle",
            "notes" to "Notizen (Optional)",
            "save" to "Transaktion speichern",
            "cancel" to "Abbrechen",
            "delete" to "Löschen",
            "language" to "Sprache der Benutzeroberfläche",
            "pref_currency" to "Bevorzugte Währung",
            "ai_insights_title" to "Gemini Finanzberater",
            "ai_btn_generate" to "Ausgabengewohnheiten analysieren",
            "ai_generating" to "Consulting Gemini um Ausgaben zu analysieren...",
            "ai_last_analyzed" to "Zuletzt aktualisiert:",
            "data_retrieved" to "%d Transaktionen gefunden.",
            "empty_state_text" to "Keine Transaktionen aufgezeichnet. Tippen Sie auf 'Wallet synchronisieren', oder fügen Sie manuell eine hinzu!",
            "card_visa" to "Google Wallet (Visa **** 7741)",
            "card_master" to "Google Wallet (Mastercard **** 3329)",
            "card_amex" to "Google Wallet (Amex **** 9951)",
            "card_loyalty" to "Google Wallet (Simulierter Ticketbeleg)",
            "manual" to "Manuell",
            "cat_food" to "Essen & Trinken",
            "cat_transport" to "Transport & Tanken",
            "cat_shopping" to "Shopping & Einzelhandel",
            "cat_entertainment" to "Unterhaltung",
            "cat_utilities" to "Rechnungen & Haushalt",
            "cat_other" to "Sonstiges",
            "wallet_pass_simulator" to "Google Wallet Pass-Simulator",
            "pass_title" to "Digitalen Beleg pushen",
            "pass_btn" to "Add to Google Wallet",
            "pass_sent_title" to "NFC-Beleg generiert!",
            "pass_sent_desc" to "Das Ticket wurde erfolgreich zu Google Wallet hinzugefügt. Simuliertes NFC-Zahlungsbeleg von",
            "clear_all_data" to "Alle Daten löschen",
            "about_app" to "Über die App",
            "about_desc" to "Eine Offline-Finanz-App, die intelligente NFC-Schnittstellen zu Google Wallet simuliert.",
            "feedback_synced" to "Synchronisation erfolgreich! %d Transaktionen geladen.",
            "field_required" to "Geben Sie einen Händler und einen positiven Betrag ein."
        ),
        AppLanguage.ARMENIAN to mapOf(
            "app_title" to "Դրամապանակի Ծախսեր",
            "nav_dashboard" to "Վահանակ",
            "nav_wallet" to "Google Wallet",
            "nav_insights" to "AI Վերլուծություն",
            "nav_settings" to "Կարգավորումներ",
            "total_expenses" to "Ամսական Ծախսեր",
            "currency_distribution" to "Ծախսերի Կատեգորիաներ",
            "wallet_status_active" to "Սինք. Միացված է Google Wallet-ի և GPay-ի ծանուցումներին",
            "sync_now" to "Սինք անել Դրամապանակը",
            "sync_desc" to "Իմպորտ անել գործարքները սիմուլյացված Google Wallet NFC քարտերից:",
            "add_manual" to "Նոր Ծախս",
            "merchant" to "Խանութ / Բրենդ",
            "amount" to "Գումար",
            "category" to "Կատեգորիա",
            "currency" to "Արժույթ",
            "source" to "Քարտ / Աղբյուր",
            "notes" to "Նշումներ (Լրացուցիչ)",
            "save" to "Պահպանել",
            "cancel" to "Չեղարկել",
            "delete" to "Ջնջել",
            "language" to "Ինտերֆեյսի Լեզու",
            "pref_currency" to "Նախընտրելի Արժույթ",
            "ai_insights_title" to "Gemini Ծախսերի Խորհրդատու",
            "ai_btn_generate" to "Վերլուծել Ծախսերը",
            "ai_generating" to "Հարցում է կատարվում Gemini AI-ին...",
            "ai_last_analyzed" to "Թարմացված է՝",
            "data_retrieved" to "Գտնվել է %d գործարք:",
            "empty_state_text" to "Գործարքներ չկան: Սեղմեք 'Սինք անել Դրամապանակը'՝ Google Wallet-ի տվյալներ ստանալու կամ ձեռքով ավելացնելու համար:",
            "card_visa" to "Google Wallet (Visa **** 7741)",
            "card_master" to "Google Wallet (Mastercard **** 3329)",
            "card_amex" to "Google Wallet (Amex **** 9951)",
            "card_loyalty" to "Google Wallet (Թվային Կտրոն)",
            "manual" to "Ձեռքով Մուտքագրում",
            "cat_food" to "Սնունդ և Սրճարաններ",
            "cat_transport" to "Տրանսպորտ և Գազ",
            "cat_shopping" to "Գնումներ և Խանութներ",
            "cat_entertainment" to "Ժամանց",
            "cat_utilities" to "Կոմունալ Ծառայություններ",
            "cat_other" to "Այլ Ծախսեր",
            "wallet_pass_simulator" to "Google Wallet-ի Կտրոնի Սիմուլյատոր",
            "pass_title" to "Ստեղծել Թվային Կտրոն",
            "pass_btn" to "Add to Google Wallet",
            "pass_sent_title" to "NFC Կտրոնը Ստեղծվեց",
            "pass_sent_desc" to "Թվային կտրոնը հաջողությամբ փոխանցվեց Google Wallet-ին: Գրանցվեց վայրկենական վճարում՝",
            "clear_all_data" to "Մաքրել բոլոր տվյալները",
            "about_app" to "Հավելվածի Մասին",
            "about_desc" to "Անցանց տվյալների բազայով հավելված, որը սիմուլյացնում է խելացի NFC կապեր Google Wallet-ի հետ, ավտոմատ իրականացնում փոխարկումներ և տրամադրում Gemini AI խորհուրդներ:",
            "feedback_synced" to "Սինքրոնիզացիան ավարտվեց: Բեռնվեց %d գործարք:",
            "field_required" to "Խնդրում ենք նշել խանութը և դրական գումար:"
        ),
        AppLanguage.RUSSIAN to mapOf(
            "app_title" to "Аналитика Кошелька",
            "nav_dashboard" to "Дашборд",
            "nav_wallet" to "Google Wallet",
            "nav_insights" to "ИИ Советник",
            "nav_settings" to "Настройки",
            "total_expenses" to "Ежемесячные Расходы",
            "currency_distribution" to "Категории Расходов",
            "wallet_status_active" to "Синхронизация: Подключено к уведомлениям Google Wallet и GPay",
            "sync_now" to "Синхронизировать Карты",
            "sync_desc" to "Импортировать транзакции из симулированных NFC-карт Google Wallet и карт лояльности.",
            "add_manual" to "Новый Расход",
            "merchant" to "Торговая Точка",
            "amount" to "Сумма",
            "category" to "Категория",
            "currency" to "Валюта",
            "source" to "Карта / Источник",
            "notes" to "Заметки (Опционально)",
            "save" to "Сохранить Транзакцию",
            "cancel" to "Отмена",
            "delete" to "Удалить",
            "language" to "Язык Интерфейса",
            "pref_currency" to "Предпочтительная Валюта",
            "ai_insights_title" to "Советник по Расходам Gemini",
            "ai_btn_generate" to "Анализировать Расходы",
            "ai_generating" to "Запрашиваем анализ у Gemini...",
            "ai_last_analyzed" to "Последнее обновление:",
            "data_retrieved" to "Найдено %d транзакций.",
            "empty_state_text" to "Нет зарегистрированных транзакций. Нажмите 'Синхронизировать Карты' для симуляции импорта из Google Wallet!",
            "card_visa" to "Google Wallet (Visa **** 7741)",
            "card_master" to "Google Wallet (Mastercard **** 3329)",
            "card_amex" to "Google Wallet (Amex **** 9951)",
            "card_loyalty" to "Google Wallet (Цифровой Талон Лояльности)",
            "manual" to "Вручную",
            "cat_food" to "Еда и Рестораны",
            "cat_transport" to "Транспорт и Бензин",
            "cat_shopping" to "Покупки и Магазины",
            "cat_entertainment" to "Развлечения",
            "cat_utilities" to "Коммунальные Услуги",
            "cat_other" to "Другие Расходы",
            "wallet_pass_simulator" to "Симулятор Купонов Google Wallet",
            "pass_title" to "Выпустить Цифровой Купон",
            "pass_btn" to "Add to Google Wallet",
            "pass_sent_title" to "NFC Купон Выпущен!",
            "pass_sent_desc" to "Купон лояльности успешно загружен в Google Wallet. Зафиксирован симулированный платеж на сумму",
            "clear_all_data" to "Очистить Все Данные",
            "about_app" to "О Приложении",
            "about_desc" to "Офлайн-бухгалтерия, симулирующая смарт-синхронизацию бесконтактных платежей Google Wallet NFC со встроенным ИИ-консультантом Gemini.",
            "feedback_synced" to "Синхронизация завершена! Загружено %d транзакций.",
            "field_required" to "Введите корректное название магазина и сумму больше нуля."
        ),
        AppLanguage.JAPANESE to mapOf(
            "app_title" to "ウォレット支出分析",
            "nav_dashboard" to "ダッシュボード",
            "nav_wallet" to "Googleウォレット",
            "nav_insights" to "AI分析",
            "nav_settings" to "設定",
            "total_expenses" to "月間総支出",
            "currency_distribution" to "カテゴリ別支出",
            "wallet_status_active" to "同期状態: Googleウォレット & GPay通知に接続中",
            "sync_now" to "ウォレット同期",
            "sync_desc" to "シミュレートされたGoogleウォレットのNFCパスおよびポイントカードから取引履歴を読み込みます。",
            "add_manual" to "支出を手動追加",
            "merchant" to "店舗名",
            "amount" to "金額",
            "category" to "カテゴリ",
            "currency" to "通貨",
            "source" to "支払いカード / 音源",
            "notes" to "メモ (任意)",
            "save" to "支出を保存",
            "cancel" to "キャンセル",
            "delete" to "削除",
            "language" to "インターフェース言語",
            "pref_currency" to "表示優先通貨",
            "ai_insights_title" to "Gemini支出アドバイザー",
            "ai_btn_generate" to "支出習慣を分析する",
            "ai_generating" to "Geminiに支出と通知データを問い合わせています...",
            "ai_last_analyzed" to "最終更新:",
            "data_retrieved" to "%d 件の取引レコードを同期しました。",
            "empty_state_text" to "支出データはありません。「ウォレット同期」をタップしてシミュレート取引を入力するか、手動で支出を記録してください。",
            "card_visa" to "Googleウォレット (Visa **** 7741)",
            "card_master" to "Googleウォレット (Mastercard **** 3329)",
            "card_amex" to "Googleウォレット (Amex **** 9951)",
            "card_loyalty" to "Googleウォレット (シミュレートパス受領証)",
            "manual" to "手動入力",
            "cat_food" to "食費・飲食",
            "cat_transport" to "交通費・ガソリン",
            "cat_shopping" to "買い物・ショッピング",
            "cat_entertainment" to "エンタメ・娯楽",
            "cat_utilities" to "公共料金・支払い",
            "cat_other" to "その他支出",
            "wallet_pass_simulator" to "Googleウォレット・パス・シミュレータ",
            "pass_title" to "デジタルパス/領収チケットの発行",
            "pass_btn" to "Add to Google Wallet",
            "pass_sent_title" to "NFCパスを発行しました！",
            "pass_sent_desc" to "カスタマイズされたパスがGoogleウォレットに正常に追加されました。即座に支出をシミュレートしました。金額：",
            "clear_all_data" to "全データをクリア",
            "about_app" to "アプリについて",
            "about_desc" to "GoogleウォレットのNFC決済イベントをシミュレートし、オフライン環境で即座に通貨変換とGemini生成型AIによる家計アドバイスを行うパーソナル分析ツールです。",
            "feedback_synced" to "ウォレット同期完了！%d 件の取引が追加されました。",
            "field_required" to "有効な店舗名と正の金額を入力してください。"
        )
    )

    fun get(key: String, lang: AppLanguage): String {
        return translations[lang]?.get(key) ?: translations[AppLanguage.ENGLISH]?.get(key) ?: key
    }
}
