package com.example.network

import com.example.BuildConfig
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import okhttp3.OkHttpClient
import retrofit2.Retrofit
import retrofit2.converter.moshi.MoshiConverterFactory
import retrofit2.http.Body
import retrofit2.http.POST
import retrofit2.http.Query
import java.util.concurrent.TimeUnit

@JsonClass(generateAdapter = true)
data class GeminiRequest(
    val contents: List<GeminiContent>,
    @Json(name = "generationConfig") val generationConfig: GeminiGenerationConfig? = null,
    @Json(name = "systemInstruction") val systemInstruction: GeminiContent? = null
)

@JsonClass(generateAdapter = true)
data class GeminiContent(
    val parts: List<GeminiPart>,
    val role: String? = null
)

@JsonClass(generateAdapter = true)
data class GeminiPart(
    val text: String
)

@JsonClass(generateAdapter = true)
data class GeminiGenerationConfig(
    val temperature: Float? = null,
    @Json(name = "responseMimeType") val responseMimeType: String? = null
)

@JsonClass(generateAdapter = true)
data class GeminiResponse(
    val candidates: List<GeminiCandidate>?
)

@JsonClass(generateAdapter = true)
data class GeminiCandidate(
    val content: GeminiContent?
)

interface GeminiApiService {
    @POST("v1beta/models/gemini-3.5-flash:generateContent")
    suspend fun generateContent(
        @Query("key") apiKey: String,
        @Body request: GeminiRequest
    ): GeminiResponse
}

object RetrofitClient {
    private const val BASE_URL = "https://generativelanguage.googleapis.com/"

    private val moshi = Moshi.Builder()
        .addLast(KotlinJsonAdapterFactory())
        .build()

    private val okHttpClient = OkHttpClient.Builder()
        .connectTimeout(60, TimeUnit.SECONDS)
        .readTimeout(60, TimeUnit.SECONDS)
        .writeTimeout(60, TimeUnit.SECONDS)
        .build()

    val service: GeminiApiService by lazy {
        Retrofit.Builder()
            .baseUrl(BASE_URL)
            .client(okHttpClient)
            .addConverterFactory(MoshiConverterFactory.create(moshi))
            .build()
            .create(GeminiApiService::class.java)
    }
}

object GeminiClient {
    suspend fun getSpendingInsights(expensesSummaryJson: String, languageName: String, currencySymbol: String): String {
        val apiKey = BuildConfig.GEMINI_API_KEY
        if (apiKey.isEmpty() || apiKey == "MY_GEMINI_API_KEY") {
            return "API Key Error: Please configure your GEMINI_API_KEY inside the Secrets panel of Google AI Studio."
        }

        val prompt = """
            You are a professional wealth advisor and budgeting assistant called 'Wallet Insight AI'.
            Review the following list of Google Wallet and transaction data for the past month:
            
            $expensesSummaryJson
            
            Current Preferred Currency for Display: $currencySymbol
            
            Provide a comprehensive, encouraging analysis of the user's spending habits. Your response:
            1. MUST be written entirely in the requested interface language: '$languageName'.
            2. Compute the total amount spent.
            3. Highlight the top category (where the most money went).
            4. Identify any potential areas of concern, waste, or unexpected spikes.
            5. Give 3 actionable, highly localized budgeting tips.
            6. Keep the formatting beautiful, clean, and highly scannable using elegant Markdown bullets or bold labels. Use the selected currency symbol ($currencySymbol) when discussing monetary sums.
            
            Always speak in an encouraging, friendly, and empowering tone. Do not include development code metadata or json tags.
        """.trimIndent()

        val request = GeminiRequest(
            contents = listOf(
                GeminiContent(
                    parts = listOf(GeminiPart(text = prompt))
                )
            ),
            generationConfig = GeminiGenerationConfig(temperature = 0.7f),
            systemInstruction = GeminiContent(
                parts = listOf(GeminiPart(text = "You are a friendly, expert financial analyst. Your goal is to guide the user towards financial wellness in their selected language."))
            )
        )

        return try {
            val response = RetrofitClient.service.generateContent(apiKey, request)
            response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text 
                ?: "No response generated by the AI model. Please verify your connection."
        } catch (e: Exception) {
            "Error: Unable to analyze spending details at this moment. Details: ${e.localizedMessage}"
        }
    }
}
